### ISSUE TITLE
Make compatible with PowerView gen 2 hubs

### ISSUE THREAD

**Issue by johnvey** [johnvey/smartthings-hd-powerview#2]
It has been reported that this handler does not work with gen 2 hubs. Opening this as a tracking issue for all gen 2 related work.

**Comment by sander76** [comment]
@johnvey Hello John.
I have official API docs available on my repo. Have a look for the pdf in the root:
https://github.com/sander76/aio-powerview-api

I work at Hunter Douglas Europe and use the above for experimenting and stuff. I can't guarantee it is always the very very latest, but I will keep it updated as much as I can.

Thanks for creating this plugin !

**Comment by johnvey** [comment]
@sander76 thanks, that's fantastic!

Yes, I believe this issue can be closed with the fix that I committed in edc354e. I'll just leave it open for a few more weeks to see if there are any other issues that get reported.

**Comment by johnvey** [comment]
@sander76 I have a long-standing question on setting vane position. The vanes open/close at half speed when activated via the Pebble remote, while they open/close at full speed when using the hub. Is there a parameter to send to the hub during its `PUT /api/shades/12345` command to perform at half speed instead? 

The reason I want to move at half speed is because it is practically silent, while moving at full speed causes the motors to generate whirring noises. I would love to make this an option in this driver.

**Comment by sander76** [comment]
@johnvey As market demands are somewhat different between US en EU market motors are also being developed in both Europe and US. Each with their own subtle differences.

What product with vanes are you referring to here ?

Sander.

**Comment by johnvey** [comment]
@sander76 this is a set of Silhouette shades, assembled in April 2017.

**Comment by sander76** [comment]
@johnvey That is a US silhouette motor. I will need to check that out myself. But I am pretty sure there currently is no extra flag for setting speeds.
